#!/usr/bin/env ruby                                                                                                                                                                                                                         
# A github post-receive hook handler, runs some shell command on each HTTP POST to PORT.                                                                                                                                                    
# sinatra.rb PORT 'SOME SHELL COMMAND'                                                                                                                                                                                              
                                                                                                                                                                                                                                            
%w{rubygems sinatra}.each{|x| require x}                                                                                                                                                                                                    
                                                                                                                                                                                                                                            
set :port, ARGV[0]                                                                                                                                                                                                                          
                                                                                                                                                                                                                                            
post '/' do                                                                                                                                                                                                                                 
  cmd = ARGV[1]                                                                                                                                                                                                                             
  print "Received POST, running: "+cmd                                                                                                                                                                                                      
  puts `#{cmd}`                                                                                                                                                                                                                             
  "ok"                                                                                                                                                                                                                                      
end
